In [14]:
def test():
    print('test() for function')
    return
test()

test() for function


In [36]:
class demo:
    def test(self):
        print("test() for the class and method")
        return
obj=demo()
obj.test()
#  demo.test() no use of self

test() for the class and method


In [39]:
class demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
    
p1=demo1()
print(p1.fact(5))

120

In [43]:
class demo2:
    def accept(self,p1,p2):
        self.a=p1
        self.b=p2
        return
    def display(s):
        print("p1=",s.a)
        print("p2=",s.b)
        
c1=demo2()
c1.accept(10,20)
c1.display()

p1= 10
p2= 20


In [34]:
class demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self,p1,p2):
        return p1+p2
    
c1=demo2(10,20)
print(c1.add(100,200))


300


In [45]:
class Person():
    #Contructor
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
    
# Derived Class
class Employee(Person):
    def isEmployee(self):
        return True
    
emp=Person("Anil")
print(emp.getName(),emp.isEmployee())

emp1=Employee("Akhil")
print(emp1.getName(),emp1.isEmployee())

Anil False
Akhil True


In [46]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [48]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [49]:
lst=[1,2,3,4]
array=np.array(lst)
array+10
print(array)

[1 2 3 4]


In [51]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [52]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)


(2, 3)
(3, 2)


In [54]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [57]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [58]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:

np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [60]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

# indexing and slicing of numpy

In [61]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [62]:
a1=np.array([(1,2,3),(4,5,6)])
print("First row:",a1[0])

First row: [1 2 3]


In [65]:
a1=np.array([(1,2,3),(4,5,6)])
print("Second row:",a1[1])

Second row: [4 5 6]


In [66]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing Column: ",a1[:,1])

Slicing Column:  [2 5]


In [67]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing Last Column: ",a1[:,2])

Slicing Last Column:  [3 6]


In [68]:
a1=np.random.normal(5,1,10)
print(a1)
print("Min Value =",np.min(a1))
print("Max Value =",np.max(a1))
print("Mean Value =",np.mean(a1))
print("Median Value =",np.median(a1))

[3.023965   4.8571409  4.18133596 5.06264248 4.81837231 4.2733989
 4.20603316 6.60461115 5.54437023 4.46876865]
Min Value = 3.023965003779017
Max Value = 6.604611146844837
Mean Value = 4.704063873566123
Median Value = 4.643570479544828


# multiply of1d arrays
# numpy.doy(x,y)

In [69]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [70]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [71]:
c1=np.array([(1,5),(6,9)])
c2=np.array([(1,3),(1,6)])
np.matmul(c1,c2)

array([[ 6, 33],
       [15, 72]])